{
 "title": "Processing metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "workspace_id",
    "query": {
     "query": "label_values(timestamps_processed_total,workspace_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data ingested per environment",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(workspace_id) (rate(http_ingested_total[1m]))",
     "legendFormat": "{{workspace_id}}"
    }
   ]
  },
  {
   "title": "Timestamps produced per environment",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(workspace_id) (rate(timestamps_produced_total[1m]))",
     "legendFormat": "{{workspace_id}}"
    }
   ]
  },
  {
   "title": "Ingest rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_ingested_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingest rate in timestamps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(timestamps_produced_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timestamps processed per environment",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(workspace_id) (rate(timestamps_processed_total[1m]))",
     "legendFormat": "{{workspace_id}}"
    }
   ]
  },
  {
   "title": "Timestamps processed in ${workspace_id}",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "sum by(consumer_group) (rate(timestamps_processed_total{workspace_id=\"${workspace_id}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downsampled rows / s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(timestamps_processed_total{consumer_group=\"1m_downsampling_v1\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}